# Program DartsCounter
# Program se snazi dojit co nejefektivnejsim zpusobem k co nejmensimu poctu 
# hodu.
#

program: main.o darts.o
	g++ -o $@ main.o darts.o

main.o: main.cpp
darts.o: darts.cpp darts.h