package gameAccountSimulator;

public enum LandType {
    FARM, LUMBER_MILL, TAVERN, STONE_QUARRY, BARRAKS, BLACKSMITH, TEMPLE,
    VILLAGE, SHIPYARD, CASTLE_KEEP, ROYAL_CASTLE, ROYAL_TRADE_ROUTE, GOLD_MINE
}